### ISSUE TITLE
EmptyContactEmailException

### ISSUE THREAD

**Issue by donjenflo** [RonasIT/laravel-swagger#104]
Hello!
Plz help with EmptyContactEmailException. 

![image](https://github.com/RonasIT/laravel-swagger/assets/116457711/7af4f807-4079-4b7b-a712-d3c3fa5f9c8d)

**Comment by Cluster2a** [comment]
@donjenflo move the contacht array to the top level.
![image](https://github.com/RonasIT/laravel-swagger/assets/84905165/a571a95b-a89d-4ee1-ae99-cb51099cd8b4)

**Comment by DenTray** [comment]
@donjenflo @Cluster2a Hi! It was a minor bug of the `dev-master` version. It should be fixed now, no need to change the config structure for now.

Please note that we always update the `config_version` param when developers should change the config structure after the package update.

**Comment by donjenflo** [comment]
Thank you for answer!
I have new trouble
![изображение](https://github.com/RonasIT/laravel-swagger/assets/116457711/5003d1f5-b7e0-4b0c-a133-4411d5004041)

**Comment by DenTray** [comment]
@Goodmain could you please make a hot fix for it?

**Comment by Goodmain** [comment]
@DenTray A made a hotfix. It now merged into master

**Comment by DenTray** [comment]
@donjenflo could you please check it after the fix?

**Comment by DenTray** [comment]
Released in [2.2 version](https://github.com/RonasIT/laravel-swagger/releases/tag/2.2)
