### ISSUE TITLE
Как сделать, что бы документация открывалась не только в testing?

### ISSUE THREAD

**Issue by ZavilenskyIlya** [RonasIT/laravel-swagger#13]
Сейчас документация работает, только если APP_ENV=testing. Как изменить, что бы открывалась в любом режиме?Сейчас ошибки

> Uncaught SyntaxError: Unexpected token <
> swagger-ui-standalone-preset.js:9 Uncaught SyntaxError: Unexpected token <
> api-doc:74 Uncaught ReferenceError: SwaggerUIBundle is not defined
>     at window.onload (api-doc:74)

**Comment by Asxer** [comment]
@ZavilenskyIlya При APP_ENV=testing запускается только сбор документации. Отображение документации должно работать в любом случае по настроенному в конфигах роуту.

**Comment by Asxer** [comment]
@ZavilenskyIlya Не могли бы вы предоставить шаги для воспроизведения ошибки и какие настройки вы имеете в config/auto-doc.php?

**Comment by ZavilenskyIlya** [comment]
Действительно, проблема не у вас, ломается из-за дебаг панели.

Извините за беспокойство и спасибо за пакет)

**Comment by Asxer** [comment]
@ZavilenskyIlya Не за что!) Обращайтесь
