### ISSUE TITLE
Add support of array rules

### ISSUE THREAD

**Issue by Asxer** [RonasIT/laravel-swagger#15]
Currently, plugin support only one format of rules, like:
```
    'some_field' => 'first_rule|second_rule|some_other_rules'
```
Because we can easily parse it to description.

Laravel supports more complex formats(array of string rules and array of validators) and in this case, we will get an exception because we are trying to send it to implode. It is only one reason why we still use string-based validations in rules. We don't know how we can process such a situation correctly. 

It is because I create this issue to discuss possible solutions.

**Comment by DenTray** [comment]
Released since 1.6.1, but better to use 2.0.0-beta
