### ISSUE TITLE
Swagger UI.  

### ISSUE THREAD

**Issue by Kladislav** [RonasIT/laravel-swagger#16]
Have a **blank** page on load docs endpoint.
The problem is ~`swagger-ui.js` files. 
As first get `Unexpected token <`, then `SwaggerUIBundle is not defined`
Any idea how to fix it?

**Comment by gluck1986** [comment]
may be problem in wrnog cotnent type of imported files. Expect text/css but receved plain/text or something. You can use more simple brouser then Chrome, for example. That problem is resolved in https://github.com/RonasIT/laravel-swagger/pull/14

**Comment by VladisloveKeam** [comment]
Fixed, put all swagger ui to public laravel folder, also you can update swagger ui, check out swagger ui repo.
