### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by Ferikl** [RonasIT/laravel-swagger#21]
Tried to install package to Laravel 6
and I cant find AutoDocTestCaseTrait trait. Can you update readme file with correct installation flow.
Also it will be great to have working examples how to use package.
Thanks for maintain !

**Comment by nemozar** [comment]
For AutoDocTestCaseTrait use **RonasIT\Support\AutoDoc\Tests\AutoDocTestCaseTrait;**.

Also error with function **elseChain**. My fix https://github.com/RonasIT/laravel-swagger/issues/18

```
<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use RonasIT\Support\AutoDoc\Tests\AutoDocTestCaseTrait;


abstract class TestCase extends BaseTestCase
{
    use CreatesApplication, AutoDocTestCaseTrait;
}
```

**Comment by DenTray** [comment]
@Ferikl readme had been updated in the last version, please use it
