### ISSUE TITLE
Laravel 7.0 requires array_get and array_collapse functions

### ISSUE THREAD

**Issue by kelvionald** [RonasIT/laravel-swagger#23]
Hi! Laravel 7.0 requires array_get and array_collapse functions.

In version Laravel 7.0, I did everything according to the instructions, but errors got out that the array_get and array_collapse functions were required to run the tests. Added them to "bootstrap/app.php" as follows:
```
if (!function_exists('array_get')) {
    function array_get($a, $k)
    {
        return Illuminate\Support\Arr::get($a, $k);
    }
}

if (!function_exists('array_collapse')) {
    function array_collapse($a)
    {
        return Illuminate\Support\Arr::collapse($a);
    }
}
```

Also, update the documentation, in tests / TestCase.php not trait is connected, but the class is inherited.
\RonasIT\Support\AutoDoc\Tests\AutoDocTestCaseTrait
=>
\RonasIT\Support\AutoDoc\Tests\AutoDocTestCase

**Comment by DenTray** [comment]
@kelvionald as legacy laravel helpers functions had been removed since Laravel 6.0, you can  use [2.0.1-beta version](https://github.com/RonasIT/laravel-swagger/releases/tag/2.0.1-beta) version or install https://packagist.org/packages/laravel/helpers
