### ISSUE TITLE
Plugin not support PHP 7.3

### ISSUE THREAD

**Issue by kelvionald** [RonasIT/laravel-swagger#24]
Laravel 7.0
PHP 7.3

Hi! I have error:
```
Fatal error: Cannot use 'String' as class name as it is reserved in D:\projects\msp_server\vendor\minime\annotations\src\Types\String.php on line 7
```
I think need use last version "minime/annotations", from 2.3.1 to 3.1.0

**Comment by DenTray** [comment]
@kelvionald it is not related to the PHP version, just to minime/annotations package. We've removed it so you can try to use the latest 2.0.0-beta version.
