### ISSUE TITLE
Support annotations 3.1.x or higher

### ISSUE THREAD

**Issue by talismandev** [RonasIT/laravel-swagger#30]
Hello, do you planning to upgrade "minime/annotations" requirement to support versions higher than 3.0.9 ?

Thanks.

**Comment by DenTray** [comment]
Hi @talismandev the "minime/annotations" package has [3.1.0](https://packagist.org/packages/minime/annotations#3.1.0) as the latest version and it requires the "nikic/php-parser" version less than 4. It blockes upgrading to the Laravel 9 so we are looking for the alternatives of "minime/annotations" package.

**Comment by DenTray** [comment]
@talismandev please follow to #35 for more information
