### ISSUE TITLE
Error when deploy

### ISSUE THREAD

**Issue by Smartel1** [RonasIT/laravel-swagger#4]
When I try to deploy my project and run "composer install --no-dev" it crashes with
` PHP Fatal error:  Class 'PHPUnit\Framework\TestCase' not found in ...`.
Thats because phpunit is require only in dev. As a temporary solution I have moved phpunit to 'require' section of composer.json. Can you please tell how to fix it correctly? 
(laravel 5.5)

**Comment by Asxer** [comment]
@Smartel1 I'm not sure If I can help you because I don't understand how does it connect with laravel-swagger plugin

**Comment by Smartel1** [comment]
Everything is ok when I dont use it =)

**Comment by Smartel1** [comment]
Even when I try to deploy your example project  (auto-doc-example) with --no-dev flag It crashes

**Comment by DenTray** [comment]
@Smartel1 you've right, the issue was related to missed phpunit requirements. You can use [2.0.1-beta](https://github.com/RonasIT/laravel-swagger/releases/tag/2.0.1-beta) version to fix it. Please let us know if you'll need an additional help.
