### ISSUE TITLE
Ability to merge docs

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-swagger#45]
Ability to set additional swagger docs in the config file to show it.

Will be helpful for using packages which provides endpoints.

**Comment by pirs1337** [comment]
@DenTray, ready for testing

**Comment by DenTray** [comment]
@pirs1337 merging works fine, thanks! But it is not clear to users how additional paths should looks like

Let's add wrapping each additional path into the `base_path` helper and add few exampes to the config description with the real paths to the doc failes.

**Comment by DenTray** [comment]
@pirs1337 still not fixed

**Comment by pirs1337** [comment]
@DenTray, fixed, ready for testing

**Comment by DenTray** [comment]
@NikitaYakovlev could you please test it?

**Comment by NikitaYakovlev** [comment]
@DenTray work as expected:

![image](https://user-images.githubusercontent.com/36948499/223957056-23426959-500a-4404-95a8-cd55d80c7397.png)

**Comment by DenTray** [comment]
I've  found a one bug, the documentation view will be broken if we set invalid file name inside the `additional_paths` config

@vitgrams could you please fix it?

**Comment by DenTray** [comment]
@vitgrams please also fix next cases:
- set non json file as additional doc
- set non open api json file

**Comment by DenTray** [comment]
@Goodmain please proceed with this one, we already has https://github.com/RonasIT/laravel-swagger/pull/82 for it

**Comment by Goodmain** [comment]
@DenTray Done and merged

**Comment by DenTray** [comment]
@Goodmain I've tested and found few enhancements:
1. Let's also report empty file and not exists file cases as exceptions
2. Let's add reference to validatable file to the exception

**Comment by DenTray** [comment]
@Goodmain exceptions works fine, but it fail documentation view now, could you please catch and report such exceptions as it works with the OpenAPIValidator Spec?

**Comment by DenTray** [comment]
@Goodmain works well now, thanks!

**Comment by DenTray** [comment]
Released in [2.2 version](https://github.com/RonasIT/laravel-swagger/releases/tag/2.2)
