### ISSUE TITLE
Update description generating logic

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-swagger#49]
1. All type-related validation rules should be skiped
2. `required` validation rule should be skipped, it already mark field with `*` symbol
3. If there is no `required` or `present` validation rule - field should be marked as "Optional"
4. Description should be started from the annotation or `attributes` method (annotation will be prioritized)

**Comment by pirs1337** [comment]
@DenTray, you can test

**Comment by DenTray** [comment]
@pirs1337 I've a strange numbers after the update

<img width="513" alt="image" src="https://user-images.githubusercontent.com/9486872/185352139-b629f424-4e0f-4a6b-80a1-f366bc271243.png">

**Comment by pirs1337** [comment]
@DenTray, ready for testing

**Comment by DenTray** [comment]
@pirs1337 looks good now, thanks!

**Comment by DenTray** [comment]
Released in [2.2 version](https://github.com/RonasIT/laravel-swagger/releases/tag/2.2)
