### ISSUE TITLE
Even more simple usage

### ISSUE THREAD

**Issue by Smartel1** [RonasIT/laravel-swagger#5]
If you will refactor SwaggerService class It would be possible not to write annotations. Descriptions of fields may be defined in 'attributes' method of FormRequest

```
protected function saveParameterDescription(&$data, $parameter, array $rulesArray, $attributes, AnnotationsBagInterface $annotations) {
        $description = array_get($attributes, $parameter);
        if (!$description) {
            $description = $annotations->get($parameter, implode(', ', $rulesArray));
        }
        $data['properties'][$parameter]['description'] = $description;
    }
```

**Comment by Smartel1** [comment]
protected function saveParameters($request, AnnotationsBagInterface $annotations) {
        $rules = (new $request)->rules();
        $attributes = (new $request)->attributes();
        $actionName = $this->getActionName($this->uri);

        if (in_array($this->method, ['get', 'delete'])) {
            $this->saveGetRequestParameters($rules, $annotations);
        } else {
            $this->savePostRequestParameters($actionName, $rules, $attributes, $annotations);
        }
    }

**Comment by Asxer** [comment]
@Smartel1 I'm sorry, we had some mess with versions of our plugins. Now it mostly fixed. But what about your issues I think we will check it not earlier than the end of the week. Further dialog I suggest to move into telegram
