### ISSUE TITLE
Change namespace to RonasIT/AutoDoc

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-swagger#62]
We need to change namespace in all classes from `RonasIT\Support\AutoDoc` to `RonasIT\AutoDoc`.

We need to change tests namespace as well

**Comment by ahmedashraf093** [comment]
@DenTray can I  do this change ?

**Comment by DenTray** [comment]
@ahmedashraf093 ok! Please proceed!

**Comment by ahmedashraf093** [comment]
@DenTray  done

**Comment by DenTray** [comment]
"

**Comment by DenTray** [comment]
@ahmedashraf093 great! thanks!
