### ISSUE TITLE
Configs logic update

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-swagger#84]
1. Use larval application name as a title field
2. Set contact email null by default and throw exception on null value to force developer to set his email

**Comment by Goodmain** [comment]
@DenTray All done and merged

**Comment by DenTray** [comment]
@Goodmain great! Works as expected! Thanks!

**Comment by DenTray** [comment]
@Goodmain I've found issue when email config is filled, but exception throwed

<img width="1247" alt="image" src="https://github.com/RonasIT/laravel-swagger/assets/9486872/ed7f3ea8-f804-4ba4-8a6d-6f217df68d97">

could you please check it?
