### ISSUE TITLE
 schema description

### ISSUE THREAD

**Issue by donjenflo** [RonasIT/laravel-swagger#96]
How can I customize the schema description for a response?

Some anolog for 
```
@OA\Response(
     *          response="200", 
     *          description="An example resource", 
     *          @OA\JsonContent(
     *              type="object", 
     *              @OA\Property(
     *                  format="string", 
     *                  default="20d338931e8d6bd9466edeba78ea7dce7c7bc01aa5cc5b4735691c50a2fe3228", 
     *                  description="token", 
     *                  property="token"
     *              ),
     *              @OA\Property(
     *                  format="application/json", 
     *                  property="user",
     *                  @OA\JsonContent(ref="#/components/schemas/UserResource") 
     *              )
     *          ),     
     *     )
```

**Comment by DenTray** [comment]
@donjenflo Hi! If I understood correctly - you need to define a status annotation for the related form request class.

Here is a default response description

<img width="400" alt="image" src="https://github.com/RonasIT/laravel-swagger/assets/9486872/7db95aca-80d0-42c8-b442-6d7b323e83f1">

and here is a custom response description

<img width="413" alt="image" src="https://github.com/RonasIT/laravel-swagger/assets/9486872/29e7d2a4-99ad-4828-bc54-7b6f47db728d">

<img width="483" alt="image" src="https://github.com/RonasIT/laravel-swagger/assets/9486872/5c4c0530-d6cb-425d-a915-828875c12929">

You can redefine description for response status by using `_{$status_code}` annotation

**Comment by donjenflo** [comment]
I wanna set informaion for current property in response
![image](https://github.com/RonasIT/laravel-swagger/assets/116457711/e414e864-7f66-4956-8be2-96743f6dddea)

**Comment by DenTray** [comment]
@donjenflo unfortunately we didn't implement such logic yet, but it good point to plan this for the 2.3 or 3.0 version

**Comment by donjenflo** [comment]
@DenTray thx for u work, i will wait this :)
