### ISSUE TITLE
Custom header key for security

### ISSUE THREAD

**Issue by donjenflo** [RonasIT/laravel-swagger#97]
I use custom key for token-header, how i can set this name in config? 
![image](https://github.com/RonasIT/laravel-swagger/assets/116457711/29a08027-4860-407f-8cdf-5e6ce1a9965d)

..jwt option give standart header name, but i need set another name

**Comment by DenTray** [comment]
@donjenflo thanks for your idea! At the moment we haven't got such ability but proceed with it after the next release
